# Generated by Django 5.2.7 on 2025-10-17 07:50

import django.db.models.deletion
import flights.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='airplanetype',
            name='airplane_image',
            field=models.ImageField(blank=True, null=True, upload_to=flights.models.create_custom_path),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
