# Generated by Django 5.2.7 on 2025-10-17 18:00

import flights.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_airplanetype_airplane_image_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airplanetype',
            name='airplane_image',
        ),
        migrations.AddField(
            model_name='airplane',
            name='airplane_image',
            field=models.ImageField(blank=True, null=True, upload_to=flights.models.create_custom_path),
        ),
    ]
